# -*- coding: utf-8 -*-
"""Simple_LinearReg_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NX8UfcSA1xrURWA2tlKAv4A5ZeO4EmI6
"""

import pandas as pd

data = pd.read_csv("insurance_data.csv")

data

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(data[["age"]],data["bought_insurance"],train_size=0.9)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train,y_train)

model.predict(x_test)

y_test

model.score(x_test,y_test)