# -*- coding: utf-8 -*-
"""LogisticRegressionModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CH_myNgKx067UI3fenUTsSrmYLRL7OV4
"""

import pandas as pd

data= pd.read_csv("HR_comma_sep.csv")

data

dum1 = pd.get_dummies(data.Department,prefix="Dt")
dum1

dum2 = pd.get_dummies(data.salary,prefix="sl")
dum2

#data.drop(["salary", "Department"],axis=1,inplace=True)
#df = pd.concat([])
data

final = pd.concat([dum1,dum2,data],axis=1)
final

x = final[["satisfaction_level","last_evaluation","number_project","average_montly_hours","time_spend_company","Work_accident","promotion_last_5years","Dt_IT","Dt_RandD","Dt_accounting","Dt_hr","Dt_management","Dt_marketing","Dt_product_mng","Dt_sales","Dt_support","Dt_technical","sl_high","sl_low","sl_medium"]]
y = final.left

from sklearn.model_selection import train_test_split

xtrain , xtest , ytrain, ytest = train_test_split(x,y,test_size=0.1)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model = model.fit(xtrain,ytrain)

model.score(xtest,ytest)

from sklearn.svm import SVC
mdl = SVC(kernel = 'rbf', C = 1, gamma = 0.1)

mdl.fit(xtrain,ytrain)

y_pred = mdl.predict(xtest)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,y_pred)
accuracy = float(cm.diagonal().sum())/len(ytest)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy)