# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbW7IqgIxtxkkctaQrk812yeQhYuQA8g
"""

import pandas as pd

from  sklearn.datasets import load_digits

data = load_digits()

df = pd.DataFrame(data.data)

df

df["target"] = data.target

df

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(df.drop(("target"),axis="columns"),df["target"],train_size=0.9 )

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(x_train,y_train)

model.score(x_test,y_test)

model_2 = RandomForestClassifier(n_estimators=40)

model_2.fit(x_train,y_train)

model_2.score(x_test,y_test)

from joblib import dump,load

dump(model,"model.ai")