# -*- coding: utf-8 -*-
"""neural network_ai_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoH7p2SRbGvatUuATUX9nSen3VCe6tDJ
"""



from sklearn.datasets import load_diabetes

data = load_diabetes()

dir(data)

import pandas as pd

data.data.shape



from sklearn.model_selection import train_test_split

xtrain, xtest , ytrain , ytest = train_test_split(data.data , data.target , test_size = 0.1)

from sklearn.ensemble import RandomForestClassifier

mdl = RandomForestClassifier()

mdl.fit(xtrain,ytrain)

mdl.score(xtest,ytest)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(xtrain,ytrain)

model.score(xtest,ytest)

from sklearn.svm import SVC

nn = SVC()

nn.fit(xtrain,ytrain)

nn.score(xtest,ytest)

from keras.layers import Dense
from keras.models import Sequential

ai = Sequential()

ai.add(Dense(32,input_dim=10,activation="relu"))
ai.add(Dense(32,activation="relu"))
ai.add(Dense(16,activation="relu"))
ai.add(Dense(1,activation="sigmoid"))

ai.compile(loss="mse",optimizer="adam",metrics=['mae'])

ai.fit(xtrain,ytrain,epochs=200,batch_size=15)

ai.evaluate(xtest,ytest)