# -*- coding: utf-8 -*-
"""SVM_AI_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuzaQiOGNex7npwj19hsnehuS5ArO_VT
"""

import pandas as pd
from sklearn.datasets import load_iris

stuff = load_iris()

dir(stuff)

dataset = pd.DataFrame(data=stuff.data,columns=stuff.feature_names)

dataset

dataset.isnull()

dataset["target"] = stuff.target

dataset

dataset["flower_name"] = dataset.target.apply(lambda x: stuff.target_names[x])

dataset

from sklearn.model_selection import train_test_split

x  =dataset.drop(["target","flower_name"],axis="columns")

y = dataset["target"]

x_train , x_test , y_train , y_test = train_test_split(x,y,train_size=0.9)

from sklearn.svm import SVC

model = SVC(kernel="linear")

model.fit(x_train,y_train)

model.score(x_test,y_test)

